### ISSUE TITLE
Переименовать класс com.eduxored.memorise.api.journal.Journal в Memo

### ISSUE THREAD

**Issue by DVEfremov** [edu-xored/memorise#13]
Переименовать класс и добавить пару полей:
- Name
- Count

**Comment by DVEfremov** [comment]
and add appropriate fields 
- Name 
- count

**Comment by DVEfremov** [comment]
Для того чтобы реализовать issue #14 нужно сначало сделать entity Memo
сечас проще всего это сделать переименовав com.eduxored.memorise.api.journal.Journal в 
com.eduxored.memorise.api.memo.Memo
и добавив  соотвествующие поля из issue #3

**Comment by aonnikov** [comment]
@Grosswood расскажи, пожалуйста, про текущий статус задачи?
