### ISSUE TITLE
Readme file should be updated

### ISSUE THREAD

**Issue by sumboid** [edu-xored/memorise#16]
Current readme steps don't work:

> - cd platform
> - mvn install
> - cd ../memorise-web-app
> - mvn install

Make the following steps to reproduce:

```
cd ../memorise-web-app
mvn clean
cd platform
mvn clean
rm -rf ~/.m2/repository/*

mvn install
cd ../memorise-web-app
mvn install
```

But this steps work as expected:

```
mvn install
cd memorise-web-app
mvn jetty:run
```

**Comment by sumboid** [comment]
Missed this comment: https://github.com/edu-xored/memorise/issues/8#issuecomment-254052460
But anyway readme file should be updated according to comment

**Comment by DVEfremov** [comment]
I've updated readme with actual steps
