### ISSUE TITLE
Реализовать сервис поиска мемов

### ISSUE THREAD

**Issue by DVEfremov** [edu-xored/memorise#21]
Необходимо:
1. Добавить интерфейс для сервиса поиска мемов, например:

```
public interface SearchMemoService {
Memo findMemo(String memoCandidateString)
}

```

Положить его нужно в пакет api модуля memorise-web-app.
1. Создать реализацию этого сервиса, который будет искать по текстовой строке кандидата в локальном кеше кандадатов и в базе данных
   Положить его нужно в пакет impl, класс должен быть package private

**Comment by aonnikov** [comment]
@zhuravlev12 расскажи, пожалуйста, про текущий статус задачи? Есть ли какие-то сложности?
