### ISSUE TITLE
Тесты в memorise-web-app не запускаются

### ISSUE THREAD

**Issue by aonnikov** [edu-xored/memorise#39]
Классы тестов находятся в не той папке. Правильное место: src/test/java/...
В результате mvn test не делает ничего. 
Необходимо убедиться, что при запуске из командной строки тесты запускаются и проходят.

**Comment by DVEfremov** [comment]
Какие трудности на данный момент ?

**Comment by aonnikov** [comment]
@Rhymmor расскажи, пожалуйста, про текущий статус задачи? Есть ли какие-то сложности?

**Comment by Rhymmor** [comment]
номер пулл реквеста: #60
