### ISSUE TITLE
Как администратор  я хочу видеть список всех мемов включая кандидатов

### ISSUE THREAD

**Issue by DVEfremov** [edu-xored/memorise#41]
Как зарегистрированный администратор я хочу видеть список всех мемов (во всех статусах)
с возможностью фильтрации по статус, по умолчанию значение фильтра = Актуальные

**Comment by DVEfremov** [comment]
Важно к демо! 

По сути реализация уже есть, осталось: 
- Добавить фильтр в список по статусу 
- Добавить столбец в таблицу "state"

Возмите плиз сегодня!

**Comment by Rhymmor** [comment]
ссылка на пулл реквест: #62
