### ISSUE TITLE
Как незарегистрированный пользователь я хочу видеть список неактульных мемов

### ISSUE THREAD

**Issue by DVEfremov** [edu-xored/memorise#42]
Как обычный незарегистрированный пользователь я хочу видеть список неактульных мемов
на домашней странице

**Comment by DVEfremov** [comment]
Это легко сделать переиспользуя уже список мемом для зарегистрированного пользователя с дополнительной фильтрацией по сттаусу или дате 

в итоге думаю лучше 
-  добавить в меню две ссылки 
  *\* "Outdated Memes" = home 
  *\* "New rising Memes"

**Comment by DVEfremov** [comment]
Нужно сделать эту задачу к демо, возмите кто-нить я помогу если что

**Comment by Rhymmor** [comment]
номер пулл реквеста: #59.
