### ISSUE TITLE
Переименовать таблицу JOURNALS в MEMOS

### ISSUE THREAD

**Issue by DVEfremov** [edu-xored/memorise#46]

**Comment by DVEfremov** [comment]
Переименовал теперь корректный мапgинг на таблицу, проверил в логах при старте апликейшена:

`Hibernate: insert into MEMOS (id, content, date, description, fileName, size, title) values (default, ?, ?, ?, ?, ?, ?)
`

**Comment by aonnikov** [comment]
@dailehok расскажи, пожалуйста, про текущий статус задачи? Я вижу, что есть какие-то коммиты. Если это финальная версия, нужно создать пулл-реквест в master.

**Comment by DVEfremov** [comment]
Сделал проверил. 
По это задаче все таблица теперь назввается MEMOS.
