### ISSUE TITLE
Запуск заданий вручную

### ISSUE THREAD

**Issue by aonnikov** [edu-xored/memorise#48]
Как администратор, я хочу запускать задания не только по расписанию, но и вручную.

**Comment by DVEfremov** [comment]
Нужно добавить в верхнее меню пункт Crawler
и добавить обработку - самое простое это дернуть json реквест и сказать ок если ок 
и текст ошибки если что то пошло не так 

думаю пока этого достаточно

**Comment by Rhymmor** [comment]
Паша же решил эту задачу?

**Comment by Firix-Pavel** [comment]
@Rhymmor, нужно реализовать нормальный запуск краулера, а так да, уже все есть.
