### ISSUE TITLE
Как незарегистрированный пользователь я должен иметь возможность зарегистрироваться 

### ISSUE THREAD

**Issue by DVEfremov** [edu-xored/memorise#52]
**Предусловия** 
* Запущенное веб приложение с произвольным напонением 

**Шаги воспроизведения** 
* Открываю домашную страницу

**Ожидаемый результат**
* Вижу ссылку которая ведет на форму регистрации 

**Фактический результат**
* Вижу панель с указанием демонстрационных логинов и паролей, которой быть не должно
![image](https://cloud.githubusercontent.com/assets/22045452/20088507/0108d85a-a5b3-11e6-9649-30b61533559b.png)

**Comment by aonnikov** [comment]
@dailehok @AyyaGalieva расскажите, пожалуйста, про текущий статус задачи? Есть ли какие-то сложности с задачей?
