### ISSUE TITLE
Typo in repo description

### ISSUE THREAD

**Issue by Inego** [edu-xored/memorise#55]
"Looking for a memes that are becoming popular" — you can't use the indefinite article with a noun in plural ;)

**Comment by DVEfremov** [comment]
So lets fix it. Your first Pull Request ;)
You could find other typos as well...

В трекре, кстати, пишем на русском в этом проекте...

**Comment by Inego** [comment]
I can't, because the GH project description is not a part of the source code.

**Comment by DVEfremov** [comment]
а

**Comment by aonnikov** [comment]
Fixed
