### ISSUE TITLE
Реализация краулера

### ISSUE THREAD

**Issue by DVEfremov** [edu-xored/memorise#6]
Реализовать базовый алгоритм работы краулера.
На вход краулеру подается искомая фраза и список адресов страниц. Кадая страница анализируется и подсчитывается количество вхождений искомой фразы.

Для реализации необходимо использовать библиотеку crowler4j.

**Comment by aonnikov** [comment]
Предлагаю начать с простого алгоритма:

Представим, что у нас уже есть потенциальный мем - текстовая фраза (неважно где мы ее взяли, может мы уже научились вычленять их из текста, либо пользователь подкинул идею).
Краулеру на входе передается эта фраза + набор урлов для проверки. Он ползает по страничкам и считает количество вхождений фразы.

Возможные пути для улучшения:
1. Поиск с учетом морфологии (разные падежи, окончания, порядок слов)
2. Переход со страниц по найденынм ссылкам и поиск на этих страницах. Можно ограничить глубину поиска.

**Comment by DVEfremov** [comment]
> 1. Поиск с учетом морфологии (разные падежи, окончания, порядок слов)
>    это можно вынести в отдельный сервис на основе готового решения например Apache Lucene для не четкого fuzzy поиска

**Comment by DVEfremov** [comment]
В целом да, мои дополнения:
- Краулер ползает по заранее определенным сайтам, процесит рекурсивно страницы каждого сайта - это я уде закомитил, 

осталось : 
- добавить в хендлер краулера парсинг страницы, вычленение мемов-кандидатов - отделный сервис со своим алгоритмом, 
- матчинг кандидатов на мемы из кеша и в базе и инкремент если найдено, добавление в кеш (Spring @Cashable на методе сервиса + ehcache настроить в xml   посже ктото может мемкешь или еще что нравится прикрутить) если не найдено.

**Comment by Rhymmor** [comment]
Базовый алгоритм кроулера реализован. Дополнения предлагаю переместить в отдельные задачи с ссылкой на эту.
