### ISSUE TITLE
Одновременное исполнение нескольких джоб crawler'а

### ISSUE THREAD

**Issue by sumboid** [edu-xored/memorise#68]
С сабжем надо будет что-то сделать, потому что, если я все правильно понял, на текущем этапе в лучшем случае две джобы будут делать одно и то же и ничего не сломают.

Надо либо проверять в момент запуска, что нет запущеных джоб, либо допускать одновременное исполнение только на разных ресурсах (если мы такое планируем делать).

**Comment by Firix-Pavel** [comment]
Так как запуск краулера могут инициировать как шедулер так и множество админов и у нас нет множества ресурсов, то предлагаю(на данном этапе) при запущенном краулере игнорировать требования его запуска и сообщать клиенту, что краулер уже запущен.

**Comment by aonnikov** [comment]
Думаю, что на данном этапе такое решение годится. Если пользователь понимает что там происходит с краулером - это уже хорошо.

**Comment by Firix-Pavel** [comment]
PR#66
