### ISSUE TITLE
[Blocker] travis job has error on master after submit

### ISSUE THREAD

**Issue by DVEfremov** [edu-xored/memorise#85]
PR https://github.com/edu-xored/memorise/pull/83 
was green but after submission it 
got error on master:

https://travis-ci.org/edu-xored/memorise

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.678 s
[INFO] Finished at: 2016-11-28T00:49:29+00:00
[INFO] Final Memory: 28M/390M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project memorise-web-app: Compilation failure: Compilation failure:
[ERROR] /home/travis/build/edu-xored/memorise/memorise-web-app/src/main/java/org/xored/edu/memorise/MemoCrawlerJob.java:[11,38] org.xored.edu.memorise.crawler.CrawlerSettings is not public in org.xored.edu.memorise.crawler; cannot be accessed from outside package
[ERROR] /home/travis/build/edu-xored/memorise/memorise-web-app/src/main/java/org/xored/edu/memorise/MemoCrawlerJob.java:[12,38] cannot find symbol
[ERROR] symbol:   class MemeCandidate
[ERROR] location: package org.xored.edu.memorise.crawler
[ERROR] /home/travis/build/edu-xored/memorise/memorise-web-app/src/main/java/org/xored/edu/memorise/MemoCrawlerJob.java:[13,42] cannot find symbol
[ERROR] symbol:   class MatchingMemeCandidate

**Comment by Firix-Pavel** [comment]
PR #86

**Comment by Firix-Pavel** [comment]
PR #86
