### ISSUE TITLE
Второй запуск краулера в течении 10 секунд приводит к ошибке 

### ISSUE THREAD

**Issue by DVEfremov** [edu-xored/memorise#89]
**Пред условия** 
* Залогинется под puclisher/publisher
* Нажать на кнопку Crawler
* Через не большой промежуток времени ~10 секунд нажать на кнопку Crawler еще раз
**Полученный результат**
 Ошибка 
![image](https://cloud.githubusercontent.com/assets/22045452/20677452/bbbd4c9a-b5c5-11e6-9675-fb57e24dcf23.png)

**Ожидаемый результат**
* Либо предупреждение что сейчас запускать пока нельзя и обяснение когда будет можно либо отсутствие ошибки

**Comment by Firix-Pavel** [comment]
Может тогда не error отправлять? А то  красная строка не очень смотрится. Или может просто alert-danger изменить/удалить

**Comment by Firix-Pavel** [comment]
Может какой-нибудь 102 "идёт обработка" информационный код отправлять?

**Comment by Firix-Pavel** [comment]
PR #92
